AllCops:
  NewCops: enable
  Exclude:
    - vendor/bundle/**/*
    - node_modules/**/*
    - db/schema.rb
    - bin/**/*

plugins:
  - rubocop-rails

require:
  - rubocop-packs

Rails/Delegate:
  Description: "Prefer delegate method for delegations."
  Enabled: false

Rails/ActionFilter:
  Description: "Enforces consistent use of action filter methods."
  Enabled: false

Rails/Date:
  Description: >-
    Checks the correct usage of date aware methods,
    such as Date.today, Date.current etc.
  Enabled: true

Rails/FindBy:
  Description: "Prefer find_by over where.first."
  Enabled: true

Rails/FindEach:
  Description: "Prefer all.find_each over all.find."
  Enabled: false

Rails/HasAndBelongsToMany:
  Description: "Prefer has_many :through to has_and_belongs_to_many."
  Enabled: false

Rails/Output:
  Description: "Checks for calls to puts, print, etc."
  Enabled: false

Rails/ReadWriteAttribute:
  Description: >-
    Checks for read_attribute(:attr) and
    write_attribute(:attr, val).
  Enabled: true

Rails/ScopeArgs:
  Description: "Checks the arguments of ActiveRecord scopes."
  Enabled: true

Rails/TimeZone:
  Description: "Checks the correct usage of time zone aware methods."
  StyleGuide: "https://github.com/bbatsov/rails-style-guide#time"
  Reference: "http://danilenko.org/2012/7/6/rails_timezones"
  Enabled: true
  EnforcedStyle: flexible

Rails/Validation:
  Description: "Use validates :attribute, hash of validations."
  Enabled: false

Rails/FilePath:
  Enabled: true
  EnforcedStyle: "arguments"

Rails/SkipsModelValidations:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/Presence:
  Enabled: false

Rails/WhereExists:
  Enabled: false

Rails/EnvironmentVariableAccess:
  AllowReads: true
